### ISSUE TITLE
Python error with Youtube video id.

### ISSUE THREAD

**Issue by itsax404** [normanlorrain/mkdocs-thumbnails#2]
Good afternoon,
I have a Python error while I reload my MkDocs website because a Youtube video id contains a `-`.
It's the error traceback : 
```python
ERROR   -  Error reading page 'équations_différentielles.md': 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\__main__.py", line 192, in <module>
    cli()
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1041, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\larma\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 971, in main
    rv = self.invoke(ctx)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1563, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1309, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 715, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\__main__.py", line 133, in serve_command
    serve.serve(
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\commands\serve.py", line 141, in serve
    config = builder()
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\commands\serve.py", line 136, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\commands\build.py", line 271, in build
    _populate_page(file.page, config, files, dirty)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\commands\build.py", line 174, in _populate_page
    page.content = config['plugins'].run_event(
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\mkdocs\plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\thumbnails\plugin.py", line 76, in on_page_content
    id = re.search( r'.*youtu.be\/(\w+).*', href).group(1)
AttributeError: 'NoneType' object has no attribute 'group
```
And the Youtube video link is `https://youtu.be/-q9M7oJ9gkI`

Have a nice day !

**Comment by normanlorrain** [comment]
Thanks for the report.  I updated the regex according to information found [here](https://webapps.stackexchange.com/questions/54443/format-for-id-of-youtube-video).

PyPI has updated version.

**Comment by itsax404** [comment]
Thanks you 👍
